In [1]:
import numpy as np

In [4]:
A = np.array([
    [3,0,0,0,0,0,0,0,0,0],
    [0,2,0,0,0,0,0,0,0,0],
    [0,0,2,0,0,0,0,0,0,0],
    [1,1,0,2,0,0,0,0,0,0],
    [1,0,1,1,3,0,0,0,0,0],
    [0,0,1,0,1,2,0,0,0,0],
    [0,0,0,0,0,0,2,0,0,0],
    [1,0,1,0,0,1,0,3,0,0],
    [1,1,0,0,0,0,0,0,2,0],
    [1,0,0,0,0,0,1,1,0,3]
])
A = A + A.T
print(A)
b = np.array([11,8,2,0,4,-4,5,18,7,11])

[[6 0 0 1 1 0 0 1 1 1]
 [0 4 0 1 0 0 0 0 1 0]
 [0 0 4 0 1 1 0 1 0 0]
 [1 1 0 4 1 0 0 0 0 0]
 [1 0 1 1 6 1 0 0 0 0]
 [0 0 1 0 1 4 0 1 0 0]
 [0 0 0 0 0 0 4 0 0 1]
 [1 0 1 0 0 1 0 6 0 1]
 [1 1 0 0 0 0 0 0 4 0]
 [1 0 0 0 0 0 1 1 0 6]]


In [20]:
sigma = np.array([7, 10, 8, 1, 6, 3, 5, 9, 4, 2]) #7 sommet périphérique
sigmaI = np.zeros(sigma.shape)
N = sigma.shape[0]
for i in range(N):
    sigmaI[i] = (N + 1) - sigma[i]
    
print(N)
print(sigma)
print(sigmaI)
#sigmaI = np.array([4,1,3,10,8,5,6,2,7,9])

10
[ 7 10  8  1  6  3  5  9  4  2]
[ 4.  1.  3. 10.  5.  8.  6.  2.  7.  9.]


In [32]:
P = np.zeros(A.shape)
for i in range(10):
    for j in range(10):
        if (i+1) == sigma[j]:
            P[i][j] = 1
print(P)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
A_prim = P.T @ A @ P
print(A_prim)

[[4. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 6. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 6. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 6. 0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 0. 4. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 1. 4. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 6. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 4. 0. 1.]
 [0. 0. 0. 1. 0. 0. 1. 0. 4. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 4.]]


In [35]:
def fit_inverse(X, y):
    """Direct method using the inverse"""
    # render X to square dimensions
    X_transp = X.T # X transpose
    X = X_transp.dot(X) # Xt * X
    y = X_transp.dot(y) # Xt * y
    #-----
    X_inv = np.linalg.inv(X) # X inverse
    return X_inv.dot(y)

In [36]:
print(fit_inverse(A,b))

[ 1.  2.  0. -1.  1. -2.  1.  3.  1.  1.]


In [44]:
b_prim = P.T @ b
print(b_prim)

[ 5. 11. 18. 11. -4.  2.  4.  7.  0.  8.]


In [43]:
x_prim = fit_inverse(A_prim, b_prim)
print(x_prim)

[ 1.  1.  3.  1. -2.  0.  1.  1. -1.  2.]


In [39]:
x = fit_inverse(P.T, x_prim)
print(x)

[ 1.  2.  0. -1.  1. -2.  1.  3.  1.  1.]
